FROM oven/bun:latest

WORKDIR /app

# Установка зависимостей
COPY package.json ./
# Копируем bun.lockb если существует
COPY bun.lockb* ./
RUN bun install

COPY . .

EXPOSE 3000

CMD ["bun", "run", "dev"]
