# Generated by Django 5.2.10 on 2026-01-13 15:15

import django.db.models.deletion
import post.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название маршрута')),
                ('departure', models.CharField(max_length=100, verbose_name='Точка отправления')),
                ('destination', models.CharField(max_length=100, verbose_name='Точка назначения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('flight_date', models.DateField(blank=True, null=True, verbose_name='Дата полета')),
                ('flight_duration', models.DurationField(blank=True, null=True, verbose_name='Длительность полета')),
                ('distance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расстояние (км)')),
                ('aircraft_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип самолета')),
                ('route_file', models.FileField(blank=True, null=True, upload_to=post.models.route_file_path, verbose_name='Файл маршрута')),
                ('is_public', models.BooleanField(default=True, verbose_name='Публичный маршрут')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_routes', to=settings.AUTH_USER_MODEL)),
                ('pilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flight_routes', to=settings.AUTH_USER_MODEL, verbose_name='Пилот')),
                ('saves', models.ManyToManyField(blank=True, related_name='saved_routes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Маршрут полета',
                'verbose_name_plural': 'Маршруты полетов',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, default='', null=True, upload_to=post.models.profile_path)),
                ('content', models.TextField()),
                ('isEdited', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_post', to=settings.AUTH_USER_MODEL)),
                ('saves', models.ManyToManyField(blank=True, related_name='saved_post', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='post.post')),
            ],
        ),
    ]
