# Generated by Django 5.2.10 on 2026-01-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightroute',
            name='departure_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта отправления'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='departure_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота отправления'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='destination_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта назначения'),
        ),
        migrations.AddField(
            model_name='flightroute',
            name='destination_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота назначения'),
        ),
    ]
