# Generated by Django 5.2.10 on 2026-01-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_flightroute_waypoints"),
    ]

    operations = [
        migrations.AddField(
            model_name="flightroute",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Публичный"),
                    ("followers", "Только подписчики"),
                    ("private", "Только я"),
                ],
                default="public",
                max_length=20,
                verbose_name="Доступ",
            ),
        ),
    ]

