# Generated by Django 5.2.11 on 2026-02-23 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Системное имя пункта меню, например: home, explore, admin_dashboard', max_length=100, unique=True, verbose_name='Ключ (slug)')),
                ('label', models.CharField(max_length=100, verbose_name='Название пункта')),
                ('location', models.CharField(choices=[('public_sidebar', 'Публичный sidebar'), ('admin_sidebar', 'Админский sidebar')], default='public_sidebar', max_length=50, verbose_name='Расположение')),
                ('is_visible_for_users', models.BooleanField(default=True, verbose_name='Виден обычным пользователям')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Раздел активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Элемент навигации',
                'verbose_name_plural': 'Элементы навигации',
                'ordering': ['location', 'order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_closed_for_public', models.BooleanField(default=False, verbose_name='Сайт закрыт для обычных пользователей')),
                ('maintenance_message', models.CharField(blank=True, help_text='Текст, который увидят обычные пользователи при закрытом сайте.', max_length=255, verbose_name='Сообщение режима обслуживания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('text', models.TextField(verbose_name='Текст жалобы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('closed', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('internal_comment', models.TextField(blank=True, verbose_name='Внутренний комментарий администратора')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_complaints', to=settings.AUTH_USER_MODEL, verbose_name='Обработал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('path', models.CharField(blank=True, max_length=255, verbose_name='Путь/страница')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP‑адрес')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='Доп. данные')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог действия пользователя',
                'verbose_name_plural': 'Логи действий пользователей',
                'ordering': ['-created'],
            },
        ),
    ]
